server:
  port: 9191
spring:
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  application:
    name: PAYMENT-SERVICE
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri:
        - http://localhost:9196
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info
info:
  application:
    name: ${spring.application.name}
    description: Payment Service